# Permalinks
permalink:           pretty

# Setup
title:               Trevor's Blog
tagline:             A Fun Place for Data Science
url:                 http://trevor2718.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Trevor Drummond
  url:               https://twitter.com/trevor_metis
  email:             trevor.drummond@thisismetis.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/trevor2718

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
